### ISSUE TITLE
日数の出力が変

### ISSUE THREAD

**Issue by itohdak** [UTokyo-SDP/git-ex-01-41#1]
DaysofMonth.javaで，
どの年，どの月も日数が30日と出力されてしまいます．
DaysofMonthクラスのメンバ関数daysofmonthが明らかに違います．

**Comment by lisakawai** [comment]
Yes, you are right. Please modify files.

**Comment by lisakawai** [comment]
If you are busy, I will do it instead.

**Comment by lisakawai** [comment]
Fixed.
