### ISSUE TITLE
Need README file

### ISSUE THREAD

**Issue by lisakawai** [UTokyo-SDP/git-ex-01-41#2]
This directory doesn't have any README files. I'm sure we need a README file.

**Comment by itohdak** [comment]
Oh, I have created README files just now....
Could you fix DaysOfMonth.java problem?

**Comment by itohdak** [comment]
And please merge my README file.
If needed, you can also edit the README file

**Comment by lisakawai** [comment]
Sure, let's use your file.

**Comment by lisakawai** [comment]
Fixed.
